"""Horos: classify a repository's token sinks and emit the reading boundary.

scan <root>    classify the tree; --json prints the boundary document,
               --write commits it to .horos/boundary.json atomically
check <root>   re-derive the boundary and name every drifted path
map <file.py>  print the file's skeleton instead of the file

Classification is fail-open: a file the rules cannot evidence stays readable
and earns no entry. The scanner stats every file but reads at most
PREFIX_BYTES of any of them, so a scan never costs more than a fraction of
what it saves.
"""

from pathlib import PurePosixPath
import argparse
import fnmatch
import json
import os
import sys

import languages

# The classifier's own reading limit. Raising it is an ask-first change once
# the tests pin it: every content rule below is defined against this prefix.
PREFIX_BYTES = 4096

# Geometry thresholds for data blobs and minified bundles. A small file is
# never a blob entry; whatever it costs, it costs almost nothing.
BLOB_MIN_BYTES = 16384
MINIFIED_MEAN_LINE_LENGTH = 400

# The maintainer's budgeted second pass: files above this size that the
# prefix leaves unclassified get two extra windows, middle and end.
LARGE_FILE_BYTES = 65536
WINDOW_BYTES = 2048

# Corroborating a candidate directory samples this many files, prefix-only,
# and needs three quarters of them to look minified, binary or generated.
DIR_SAMPLE_FILES = 8

LOCKFILE_NAMES = frozenset(
    {
        "bun.lockb",
        "Cargo.lock",
        "composer.lock",
        "flake.lock",
        "Gemfile.lock",
        "go.sum",
        "package-lock.json",
        "packages.lock.json",
        "Pipfile.lock",
        "pnpm-lock.yaml",
        "poetry.lock",
        "uv.lock",
        "yarn.lock",
    }
)

GENERATED_MARKERS = (
    "do not edit",
    "@generated",
    "code generated by",
    "auto-generated",
    "autogenerated",
    "automatically generated",
)

GENERATED_DIR_NAMES = frozenset({"build", "dist", "out", "storybook-static"})

VENDORED_DIR_NAMES = frozenset(
    {"bower_components", "node_modules", "third_party", "thirdparty", "vendor", "vendored"}
)

# Never walked, never listed: not source and not a sink worth recording.
SKIPPED_DIR_NAMES = frozenset({".git", ".horos", "__pycache__"})


def read_prefix(path):
    """Return the first PREFIX_BYTES of the file, raw."""
    with open(path, "rb") as handle:
        return handle.read(PREFIX_BYTES)


# Git attributes are directory-scoped; each file is read up to this cap,
# per the maintainer's refinement specification.
ATTRIBUTES_CAP = 65536


def parse_attribute_file(path):
    """Parse one .gitattributes file for unnegated linguist-vendored and
    linguist-generated patterns, fail-open on anything unparseable."""
    rules = []
    if not os.path.isfile(path) or os.path.islink(path):
        return rules
    try:
        with open(path, "rb") as handle:
            text = handle.read(ATTRIBUTES_CAP).decode("utf-8", errors="replace")
    except OSError:
        return rules
    for line in text.splitlines():
        parts = line.split()
        if len(parts) < 2 or parts[0].startswith("#"):
            continue
        for category, attribute in (
            ("vendored", "linguist-vendored"),
            ("generated", "linguist-generated"),
        ):
            if attribute in parts[1:] or f"{attribute}=true" in parts[1:]:
                rules.append((parts[0].lstrip("/"), category, attribute))
    return rules


def gitattributes_rules(root):
    """The repository root's rules; nested files join during the walk."""
    return parse_attribute_file(os.path.join(root, ".gitattributes"))


def _ancestors_innermost_first(relpath):
    """The directory chain that scopes a path, innermost first, root last."""
    parts = PurePosixPath(relpath).parts[:-1]
    chain = []
    for i in range(len(parts), -1, -1):
        chain.append("/".join(parts[:i]) or ".")
    return chain


def match_attribute_scopes(scopes, relpath):
    """Match a path against every .gitattributes scope covering it,
    innermost scope first, so a deeper file overrides nothing outside its
    own directory but speaks first inside it."""
    for scope in _ancestors_innermost_first(relpath):
        rules = scopes.get(scope)
        if not rules:
            continue
        local = relpath if scope == "." else relpath[len(scope) + 1 :]
        for pattern, category, attribute in rules:
            candidates = [pattern]
            if pattern.endswith("/**"):
                candidates.append(pattern[: -len("/**")] + "/*")
            for candidate in candidates:
                if fnmatch.fnmatch(local, candidate) or fnmatch.fnmatch(
                    PurePosixPath(local).name, candidate
                ):
                    where = ".gitattributes" if scope == "." else f"{scope}/.gitattributes"
                    return category, f"{attribute} for {pattern!r} in {where}"
    return None


def match_gitattributes(rules, relpath):
    """Root-scope matching kept for callers holding a flat rule list."""
    return match_attribute_scopes({".": rules}, relpath)


# Leading bytes that name a binary format outright; more reliable than a
# null byte happening to appear inside the prefix.
FILE_SIGNATURES = (
    (b"\x89PNG\r\n\x1a\n", "png"),
    (b"\xff\xd8\xff", "jpeg"),
    (b"GIF87a", "gif"),
    (b"GIF89a", "gif"),
    (b"PK\x03\x04", "zip"),
    (b"%PDF", "pdf"),
    (b"\x00asm", "webassembly"),
    (b"wOFF", "woff"),
    (b"wOF2", "woff2"),
    (b"\x1f\x8b", "gzip"),
    (b"\x7fELF", "elf"),
    (b"OTTO", "opentype"),
    (b"RIFF", "riff"),
)


def match_signature(prefix):
    for magic, name in FILE_SIGNATURES:
        if prefix.startswith(magic):
            return name
    return None


def classify_content(name, size, prefix):
    """Content rules over the bounded prefix, most decisive first.

    Returns (category, evidence) or None. Order matters: a null byte makes
    every later text heuristic meaningless, so binary wins outright.
    """
    signature = match_signature(prefix)
    if signature is not None:
        return "binary", f"file signature {signature}", "hard"

    if b"\x00" in prefix:
        return "binary", "null byte in the first %d bytes" % PREFIX_BYTES, "candidate"

    text = prefix.decode("utf-8", errors="replace")
    lowered = text.lower()
    # SVG before the marker scan: a tool-stamped SVG is still an asset, and
    # asset is the more specific truth about it.
    if name.endswith(".svg") and "<svg" in lowered:
        return (
            "asset",
            f"svg root element in the first {PREFIX_BYTES} bytes",
            "candidate",
        )

    for marker in GENERATED_MARKERS:
        if marker in lowered:
            return (
                "generated",
                f"marker {marker!r} in the first {PREFIX_BYTES} bytes",
                "hard",
            )

    if name.endswith(".map") and '"mappings"' in text:
        return (
            "generated",
            'sourcemap: name ends .map and prefix carries "mappings"',
            "hard",
        )

    if size >= BLOB_MIN_BYTES:
        newlines = prefix.count(b"\n")
        if newlines == 0:
            return (
                "blob",
                f"no newline in the first {PREFIX_BYTES} bytes of {size} bytes",
                "candidate",
            )
        if len(prefix) // (newlines + 1) > MINIFIED_MEAN_LINE_LENGTH:
            return (
                "blob",
                "mean line length above %d in the first %d bytes"
                % (MINIFIED_MEAN_LINE_LENGTH, PREFIX_BYTES),
                "candidate",
            )
    return None


def classify_windows(fullpath, name, size):
    """The selective second pass: two extra windows for a large file the
    prefix left unclassified. A marker found here is hard; geometry stays a
    candidate wherever it is found."""
    offsets = (size // 2, max(0, size - WINDOW_BYTES))
    with open(fullpath, "rb") as handle:
        for offset in offsets:
            handle.seek(offset)
            window = handle.read(WINDOW_BYTES)
            lowered = window.decode("utf-8", errors="replace").lower()
            for marker in GENERATED_MARKERS:
                if marker in lowered:
                    return (
                        "generated",
                        f"marker {marker!r} in a {WINDOW_BYTES}-byte window at offset {offset}",
                        "hard",
                    )
            newlines = window.count(b"\n")
            if newlines == 0:
                return (
                    "blob",
                    f"no newline in a {WINDOW_BYTES}-byte window at offset {offset} of {size} bytes",
                    "candidate",
                )
            if len(window) // (newlines + 1) > MINIFIED_MEAN_LINE_LENGTH:
                return (
                    "blob",
                    "mean line length above %d in a window at offset %d"
                    % (MINIFIED_MEAN_LINE_LENGTH, offset),
                    "candidate",
                )
    return None


def classify_file(root, relpath):
    """Classify one file; None means it stays readable.

    Raises OSError when the file cannot be statted or read, so the caller
    can count it as skipped rather than silently readable. Symlinks are
    refused here as well as in the walk: this function is public, and a
    caller handing it a link must not make the scanner read outside root.
    """
    fullpath = os.path.join(root, relpath)
    if os.path.islink(fullpath):
        return None
    name = PurePosixPath(relpath).name
    size = os.stat(fullpath).st_size

    if name in LOCKFILE_NAMES:
        return {
            "path": relpath,
            "category": "lockfile",
            "bytes": size,
            "evidence": f"lockfile name {name}",
            "grade": "hard",
        }

    if name.endswith(".sql") and "migrations" in PurePosixPath(relpath).parts[:-1]:
        return {
            "path": relpath,
            "category": "generated",
            "bytes": size,
            "evidence": "sql file under a migrations directory segment",
            "grade": "candidate",
        }

    prefix = read_prefix(fullpath)
    verdict = classify_content(name, size, prefix)
    if verdict is None and size > LARGE_FILE_BYTES:
        verdict = classify_windows(fullpath, name, size)
    if verdict is None:
        return None
    category, evidence, grade = verdict
    return {
        "path": relpath,
        "category": category,
        "bytes": size,
        "evidence": evidence,
        "grade": grade,
    }


def _suffix_of(name):
    """The name's last suffix, lowercased; a leading dot is not a suffix."""
    if "." in name[1:]:
        return "." + name.rsplit(".", 1)[1].lower()
    return "(no suffix)"


def _census_add(tally, name, size, in_boundary):
    if tally is None:
        return
    row = tally.setdefault(_suffix_of(name), {"files": 0, "bytes": 0, "boundary_bytes": 0})
    row["files"] += 1
    row["bytes"] += size
    if in_boundary:
        row["boundary_bytes"] += size


PACKAGE_MANAGER_DIRS = frozenset({"bower_components", "node_modules"})


def corroborate_directory(fulldir, dirname):
    """The second signal a candidate directory name needs before it excludes
    as hard: a known package-manager structure, or a deterministic sample of
    its first files looking overwhelmingly minified, binary or generated.
    Returns the corroborating evidence, or None."""
    if dirname in PACKAGE_MANAGER_DIRS:
        try:
            children = sorted(os.listdir(fulldir))
        except OSError:
            children = []
        for child in children:
            manifest = os.path.join(fulldir, child, "package.json")
            if os.path.isfile(manifest) and not os.path.islink(manifest):
                return f"package-manager structure ({child}/package.json)"

    sampled = []
    for dirpath, dirnames, filenames in os.walk(fulldir, followlinks=False):
        dirnames[:] = sorted(d for d in dirnames if d not in SKIPPED_DIR_NAMES)
        for filename in sorted(filenames):
            fullpath = os.path.join(dirpath, filename)
            if os.path.islink(fullpath):
                continue
            sampled.append(fullpath)
            if len(sampled) >= DIR_SAMPLE_FILES:
                break
        if len(sampled) >= DIR_SAMPLE_FILES:
            break
    if not sampled:
        return None
    hits = 0
    for fullpath in sampled:
        try:
            size = os.stat(fullpath).st_size
            prefix = read_prefix(fullpath)
        except OSError:
            continue
        name = os.path.basename(fullpath)
        verdict = classify_content(name, max(size, BLOB_MIN_BYTES), prefix)
        if verdict is not None:
            hits += 1
    needed = max(1, (3 * len(sampled) + 3) // 4)
    if hits >= needed:
        return f"sample: {hits} of {len(sampled)} files minified, binary or generated"
    return None


def directory_entry(root, relpath, category, evidence, tally=None, grade="hard"):
    """Aggregate a vendored or generated directory into one entry."""
    total = 0
    files = 0
    for dirpath, dirnames, filenames in os.walk(
        os.path.join(root, relpath), followlinks=False
    ):
        dirnames[:] = sorted(d for d in dirnames if d not in SKIPPED_DIR_NAMES)
        for filename in sorted(filenames):
            fullpath = os.path.join(dirpath, filename)
            if os.path.islink(fullpath):
                continue
            try:
                size = os.stat(fullpath).st_size
            except OSError:
                continue
            total += size
            files += 1
            _census_add(tally, filename, size, in_boundary=True)
    return {
        "path": relpath + "/",
        "category": category,
        "bytes": total,
        "files": files,
        "evidence": evidence,
        "grade": grade,
    }


def scan_tree(root, census=False):
    """Walk the tree and return entries plus the counts a quiet run reports.

    With census=True the same walk also tallies every file by suffix, so the
    census can never describe a different tree than the boundary does; the
    result gains a "census" key and nothing else changes."""
    root = os.path.abspath(root)
    scopes = {}
    tally = {} if census else None
    entries = []
    candidates = []
    walked = 0
    skipped_unreadable = 0

    for dirpath, dirnames, filenames in os.walk(root, followlinks=False):
        relative_dir = os.path.relpath(dirpath, root)
        if ".gitattributes" in filenames:
            scope_key = "." if relative_dir == "." else relative_dir.replace(os.sep, "/")
            rules = parse_attribute_file(os.path.join(dirpath, ".gitattributes"))
            if rules:
                scopes[scope_key] = rules
        keep = []
        for dirname in sorted(dirnames):
            if dirname in SKIPPED_DIR_NAMES:
                continue
            child = os.path.join(dirpath, dirname)
            if os.path.islink(child):
                continue
            relpath = dirname if relative_dir == "." else f"{relative_dir}/{dirname}"
            relpath = relpath.replace(os.sep, "/")
            named_category = None
            if dirname in VENDORED_DIR_NAMES:
                named_category = "vendored"
            elif dirname in GENERATED_DIR_NAMES:
                named_category = "generated"
            if named_category is not None:
                corroboration = corroborate_directory(child, dirname)
                if corroboration is not None:
                    entries.append(
                        directory_entry(
                            root,
                            relpath,
                            named_category,
                            f"directory name {dirname} corroborated by {corroboration}",
                            tally,
                        )
                    )
                    continue
                # Name alone is a candidate signal; the subtree is walked
                # file by file instead of being excluded.
                candidates.append(
                    directory_entry(
                        root,
                        relpath,
                        named_category,
                        f"directory name {dirname} alone, uncorroborated",
                        None,
                        grade="candidate",
                    )
                )
                keep.append(dirname)
                continue
            matched = match_attribute_scopes(scopes, relpath + "/")
            if matched is not None:
                entries.append(
                    directory_entry(root, relpath, matched[0], matched[1], tally)
                )
                continue
            keep.append(dirname)
        dirnames[:] = keep

        for filename in sorted(filenames):
            fullpath = os.path.join(dirpath, filename)
            if os.path.islink(fullpath):
                continue
            relpath = filename if relative_dir == "." else f"{relative_dir}/{filename}"
            relpath = relpath.replace(os.sep, "/")
            walked += 1
            matched = match_attribute_scopes(scopes, relpath)
            if matched is not None:
                try:
                    size = os.stat(fullpath).st_size
                except OSError:
                    skipped_unreadable += 1
                    continue
                entries.append(
                    {
                        "path": relpath,
                        "category": matched[0],
                        "bytes": size,
                        "evidence": matched[1],
                        "grade": "hard",
                    }
                )
                _census_add(tally, filename, size, in_boundary=True)
                continue
            try:
                entry = classify_file(root, relpath)
            except OSError:
                skipped_unreadable += 1
                continue
            if entry is not None and entry["grade"] == "hard":
                entries.append(entry)
                _census_add(tally, filename, entry["bytes"], in_boundary=True)
            elif entry is not None:
                candidates.append(entry)
                _census_add(tally, filename, entry["bytes"], in_boundary=False)
            elif tally is not None:
                try:
                    _census_add(
                        tally, filename, os.stat(fullpath).st_size, in_boundary=False
                    )
                except OSError:
                    skipped_unreadable += 1

    entries.sort(key=lambda entry: entry["path"])
    candidates.sort(key=lambda entry: entry["path"])
    counts = {"files_walked": walked, "files_skipped_unreadable": skipped_unreadable}
    for entry in entries:
        key = "bytes_" + entry["category"]
        counts[key] = counts.get(key, 0) + entry["bytes"]
    result = {"entries": entries, "candidates": candidates, "counts": counts}
    if tally is not None:
        result["census"] = tally
    return result


BOUNDARY_RELPATH = ".horos/boundary.json"
BOUNDARY_SCHEMA = 2
CANDIDATES_RELPATH = ".horos/candidates.json"

# Printed after a boundary write, for the adopting repository's AGENTS.md or
# CLAUDE.md. This is the whole bridge to agents that have never heard of
# Horos: harnesses load those files at session start, so the discipline
# travels with the repository instead of with this skill.
ADOPTION_STANZA = """\
Paste this into the repository's AGENTS.md or CLAUDE.md so agents without
Horos inherit the boundary:

## Reading boundary

Before reading this repository broadly, consult `.horos/boundary.json`.
Every path listed there is a classified token sink carrying the evidence
that earned its entry; leave those paths unread unless the task demands
one. The boundary is fail-open: what it omits is merely unproven. It never
applies during security review; during any audit, review or incident work,
read as if no boundary exists.
"""


def boundary_document(result):
    """The committed artefact: schema-tagged, no timestamps, no absolute paths."""
    return {
        "schema": BOUNDARY_SCHEMA,
        "tool": "horos",
        "entries": result["entries"],
        "counts": result["counts"],
    }


def render(document):
    """One canonical byte form, so equal documents are equal files."""
    return json.dumps(document, indent=2, sort_keys=True) + "\n"


def _write_atomic(root, relpath, text):
    """Write atomically: a killed run leaves the old artefact or the new one."""
    directory = os.path.join(root, os.path.dirname(relpath))
    os.makedirs(directory, exist_ok=True)
    final = os.path.join(root, relpath)
    # Per-process name: two concurrent scans must not unlink each other's
    # half-written temporary in the finally block below.
    temporary = f"{final}.{os.getpid()}.tmp"
    try:
        with open(temporary, "w", encoding="utf-8") as handle:
            handle.write(text)
        os.replace(temporary, final)
    finally:
        if os.path.exists(temporary):
            os.unlink(temporary)


def write_boundary(root, document):
    _write_atomic(root, BOUNDARY_RELPATH, render(document))


def candidates_document(result):
    """The advisory report: candidate findings a maintainer can promote to a
    repository-specific rule. Candidates never bind an agent."""
    counts = {}
    for entry in result["candidates"]:
        key = "bytes_" + entry["category"]
        counts[key] = counts.get(key, 0) + entry["bytes"]
    return {
        "schema": BOUNDARY_SCHEMA,
        "tool": "horos",
        "entries": result["candidates"],
        "counts": counts,
    }


def write_candidates(root, document):
    _write_atomic(root, CANDIDATES_RELPATH, render(document))


CENSUS_RELPATH = ".horos/census.json"
CENSUS_SCHEMA = 1


def census_document(result):
    """The per-filetype breakdown: exact integers, sorted rows, no clocks."""
    rows = [
        {"suffix": suffix, **row} for suffix, row in result["census"].items()
    ]
    rows.sort(key=lambda row: (-row["bytes"], row["suffix"]))
    return {
        "schema": CENSUS_SCHEMA,
        "tool": "horos",
        "total_files": sum(row["files"] for row in rows),
        "total_bytes": sum(row["bytes"] for row in rows),
        "rows": rows,
    }


def write_census(root, document):
    _write_atomic(root, CENSUS_RELPATH, render(document))


def load_boundary(root):
    with open(os.path.join(root, BOUNDARY_RELPATH), encoding="utf-8") as handle:
        return json.load(handle)


def diff_documents(committed, fresh):
    """Name every drifted path; a symmetric compare, so a committed entry the
    tree no longer evidences drifts exactly like a new sink the boundary lacks.
    """
    old = {entry["path"]: entry for entry in committed.get("entries", [])}
    new = {entry["path"]: entry for entry in fresh.get("entries", [])}
    drifted = []
    for path in sorted(set(old) | set(new)):
        if path not in new:
            drifted.append((path, "in the boundary but no longer evidenced by the tree"))
        elif path not in old:
            drifted.append((path, "evidenced by the tree but missing from the boundary"))
        elif old[path] != new[path]:
            drifted.append((path, "entry changed: %s -> %s" % (old[path], new[path])))
    return drifted


def check_tree(root, out=None):
    out = out if out is not None else sys.stdout
    try:
        committed = load_boundary(root)
    except FileNotFoundError:
        print(f"horos: no boundary at {BOUNDARY_RELPATH}; run scan --write", file=out)
        return 2
    except (OSError, json.JSONDecodeError) as error:
        print(f"horos: unreadable boundary: {error}", file=out)
        return 2
    result = scan_tree(root)
    fresh = boundary_document(result)
    drifted = diff_documents(committed, fresh)
    candidate_drift = []
    try:
        with open(os.path.join(root, CANDIDATES_RELPATH), encoding="utf-8") as handle:
            committed_candidates = json.load(handle)
    except (OSError, json.JSONDecodeError):
        committed_candidates = None
    if committed_candidates is not None:
        candidate_drift = diff_documents(
            committed_candidates, candidates_document(result)
        )
    for path, reason in candidate_drift:
        print(f"candidate drift: {path}: {reason}", file=out)
    if not drifted:
        print("boundary matches the tree", file=out)
        return 0
    for path, reason in drifted:
        print(f"drift: {path}: {reason}", file=out)
    print(f"{len(drifted)} path(s) drifted", file=out)
    return 1


def map_file(path, out=None):
    """Print a file's skeleton via its language extractor; orientation
    without the read."""
    out = out if out is not None else sys.stdout
    extractor = None
    for suffix in sorted(languages.EXTRACTORS, key=len, reverse=True):
        if path.endswith(suffix):
            extractor = languages.EXTRACTORS[suffix]
            break
    if extractor is None:
        print(f"horos: map supports {languages.supported()}, not {path}", file=out)
        return 2
    try:
        with open(path, "rb") as handle:
            source = handle.read().decode("utf-8", errors="replace")
    except OSError as error:
        print(f"horos: cannot read {path}: {error}", file=out)
        return 2
    return extractor(path, source, out)


def main(argv=None):
    parser = argparse.ArgumentParser(prog="horos", description=__doc__)
    subparsers = parser.add_subparsers(dest="command", required=True)
    scan = subparsers.add_parser("scan", help="classify a tree")
    scan.add_argument("root", help="directory to scan")
    scan.add_argument(
        "--json", action="store_true", help="print the boundary document"
    )
    scan.add_argument(
        "--write", action="store_true", help=f"write {BOUNDARY_RELPATH} atomically"
    )
    scan.add_argument(
        "--census",
        action="store_true",
        help=f"per-filetype breakdown; with --write it goes to {CENSUS_RELPATH}",
    )
    checker = subparsers.add_parser("check", help="verify the committed boundary")
    checker.add_argument("root", help="directory to check")
    mapper = subparsers.add_parser("map", help="print a Python file's skeleton")
    mapper.add_argument("file", help="Python file to map")
    args = parser.parse_args(argv)

    if args.command == "map":
        return map_file(args.file)

    if not os.path.isdir(args.root):
        print(f"horos: not a directory: {args.root}", file=sys.stderr)
        return 2

    if args.command == "check":
        return check_tree(args.root)

    result = scan_tree(args.root, census=args.census)

    if args.census:
        document = census_document(result)
        if args.write:
            write_census(args.root, document)
        if args.json:
            sys.stdout.write(render(document))
        else:
            total = document["total_bytes"] or 1
            for row in document["rows"]:
                share = 100 * row["bytes"] / total
                print(
                    f"{row['suffix']}  files={row['files']}  bytes={row['bytes']}"
                    f"  share={share:.1f}%  boundary_bytes={row['boundary_bytes']}"
                )
            print(f"total: {document['total_files']} files, {document['total_bytes']} bytes")
        return 0

    document = boundary_document(result)
    advisory = candidates_document(result)
    if args.write:
        write_boundary(args.root, document)
        write_candidates(args.root, advisory)
    if args.json:
        sys.stdout.write(render(document))
    else:
        for key, value in sorted(document["counts"].items()):
            print(f"{key}: {value}")
        print(f"entries: {len(document['entries'])}")
        print(f"candidates: {len(advisory['entries'])}")
        if args.write:
            print()
            print(ADOPTION_STANZA, end="")
    return 0


if __name__ == "__main__":
    sys.exit(main())
