"""Horos: classify a repository's token sinks and emit the reading boundary.

scan <root>    classify the tree; --json prints the boundary document,
               --write commits it to .horos/boundary.json atomically
check <root>   re-derive the boundary and name every drifted path
map <file.py>  print the file's skeleton instead of the file

Classification is fail-open: a file the rules cannot evidence stays readable
and earns no entry. The scanner stats every file but reads at most
PREFIX_BYTES of any of them, so a scan never costs more than a fraction of
what it saves.
"""

from pathlib import PurePosixPath
import argparse
import fnmatch
import json
import os
import sys

import languages

# The classifier's own reading limit. Raising it is an ask-first change once
# the tests pin it: every content rule below is defined against this prefix.
PREFIX_BYTES = 4096

# Geometry thresholds for data blobs and minified bundles. A small file is
# never a blob entry; whatever it costs, it costs almost nothing.
BLOB_MIN_BYTES = 16384
MINIFIED_MEAN_LINE_LENGTH = 400

LOCKFILE_NAMES = frozenset(
    {
        "bun.lockb",
        "Cargo.lock",
        "composer.lock",
        "flake.lock",
        "Gemfile.lock",
        "go.sum",
        "package-lock.json",
        "packages.lock.json",
        "Pipfile.lock",
        "pnpm-lock.yaml",
        "poetry.lock",
        "uv.lock",
        "yarn.lock",
    }
)

GENERATED_MARKERS = (
    "do not edit",
    "@generated",
    "code generated by",
    "auto-generated",
    "autogenerated",
    "automatically generated",
)

GENERATED_DIR_NAMES = frozenset({"build", "dist", "out", "storybook-static"})

VENDORED_DIR_NAMES = frozenset(
    {"bower_components", "node_modules", "third_party", "thirdparty", "vendor", "vendored"}
)

# Never walked, never listed: not source and not a sink worth recording.
SKIPPED_DIR_NAMES = frozenset({".git", ".horos", "__pycache__"})


def read_prefix(path):
    """Return the first PREFIX_BYTES of the file, raw."""
    with open(path, "rb") as handle:
        return handle.read(PREFIX_BYTES)


def gitattributes_rules(root):
    """Parse linguist-vendored and linguist-generated patterns, fail-open.

    Only the repository-root .gitattributes is consulted, and only patterns
    whose attribute is an unnegated linguist-vendored or linguist-generated.
    Anything unparseable is skipped rather than guessed at.
    """
    rules = []
    path = os.path.join(root, ".gitattributes")
    if not os.path.isfile(path) or os.path.islink(path):
        return rules
    try:
        text = read_prefix(path).decode("utf-8", errors="replace")
    except OSError:
        return rules
    for line in text.splitlines():
        parts = line.split()
        if len(parts) < 2 or parts[0].startswith("#"):
            continue
        for category, attribute in (
            ("vendored", "linguist-vendored"),
            ("generated", "linguist-generated"),
        ):
            if attribute in parts[1:] or f"{attribute}=true" in parts[1:]:
                rules.append((parts[0].lstrip("/"), category, attribute))
    return rules


def match_gitattributes(rules, relpath):
    for pattern, category, attribute in rules:
        candidates = [pattern]
        if pattern.endswith("/**"):
            candidates.append(pattern[: -len("/**")] + "/*")
        for candidate in candidates:
            if fnmatch.fnmatch(relpath, candidate) or fnmatch.fnmatch(
                PurePosixPath(relpath).name, candidate
            ):
                return category, f"{attribute} for {pattern!r} in .gitattributes"
    return None


def classify_content(name, size, prefix):
    """Content rules over the bounded prefix, most decisive first.

    Returns (category, evidence) or None. Order matters: a null byte makes
    every later text heuristic meaningless, so binary wins outright.
    """
    if b"\x00" in prefix:
        return "binary", "null byte in the first %d bytes" % PREFIX_BYTES

    text = prefix.decode("utf-8", errors="replace")
    lowered = text.lower()
    # SVG before the marker scan: a tool-stamped SVG is still an asset, and
    # asset is the more specific truth about it.
    if name.endswith(".svg") and "<svg" in lowered:
        return "asset", f"svg root element in the first {PREFIX_BYTES} bytes"

    for marker in GENERATED_MARKERS:
        if marker in lowered:
            return "generated", f"marker {marker!r} in the first {PREFIX_BYTES} bytes"

    if name.endswith(".map") and '"mappings"' in text:
        return "generated", 'sourcemap: name ends .map and prefix carries "mappings"'

    if size >= BLOB_MIN_BYTES:
        newlines = prefix.count(b"\n")
        if newlines == 0:
            return "blob", f"no newline in the first {PREFIX_BYTES} bytes of {size} bytes"
        if len(prefix) // (newlines + 1) > MINIFIED_MEAN_LINE_LENGTH:
            return (
                "blob",
                "mean line length above %d in the first %d bytes"
                % (MINIFIED_MEAN_LINE_LENGTH, PREFIX_BYTES),
            )
    return None


def classify_file(root, relpath):
    """Classify one file; None means it stays readable.

    Raises OSError when the file cannot be statted or read, so the caller
    can count it as skipped rather than silently readable. Symlinks are
    refused here as well as in the walk: this function is public, and a
    caller handing it a link must not make the scanner read outside root.
    """
    fullpath = os.path.join(root, relpath)
    if os.path.islink(fullpath):
        return None
    name = PurePosixPath(relpath).name
    size = os.stat(fullpath).st_size

    if name in LOCKFILE_NAMES:
        return {
            "path": relpath,
            "category": "lockfile",
            "bytes": size,
            "evidence": f"lockfile name {name}",
        }

    if name.endswith(".sql") and "migrations" in PurePosixPath(relpath).parts[:-1]:
        return {
            "path": relpath,
            "category": "generated",
            "bytes": size,
            "evidence": "sql file under a migrations directory segment",
        }

    prefix = read_prefix(fullpath)
    verdict = classify_content(name, size, prefix)
    if verdict is None:
        return None
    category, evidence = verdict
    return {"path": relpath, "category": category, "bytes": size, "evidence": evidence}


def directory_entry(root, relpath, category, evidence):
    """Aggregate a vendored or generated directory into one entry."""
    total = 0
    files = 0
    for dirpath, dirnames, filenames in os.walk(
        os.path.join(root, relpath), followlinks=False
    ):
        dirnames[:] = sorted(d for d in dirnames if d not in SKIPPED_DIR_NAMES)
        for filename in sorted(filenames):
            fullpath = os.path.join(dirpath, filename)
            if os.path.islink(fullpath):
                continue
            try:
                total += os.stat(fullpath).st_size
            except OSError:
                continue
            files += 1
    return {
        "path": relpath + "/",
        "category": category,
        "bytes": total,
        "files": files,
        "evidence": evidence,
    }


def scan_tree(root):
    """Walk the tree and return entries plus the counts a quiet run reports."""
    root = os.path.abspath(root)
    rules = gitattributes_rules(root)
    entries = []
    walked = 0
    skipped_unreadable = 0

    for dirpath, dirnames, filenames in os.walk(root, followlinks=False):
        relative_dir = os.path.relpath(dirpath, root)
        keep = []
        for dirname in sorted(dirnames):
            if dirname in SKIPPED_DIR_NAMES:
                continue
            child = os.path.join(dirpath, dirname)
            if os.path.islink(child):
                continue
            relpath = dirname if relative_dir == "." else f"{relative_dir}/{dirname}"
            relpath = relpath.replace(os.sep, "/")
            if dirname in VENDORED_DIR_NAMES:
                entries.append(
                    directory_entry(root, relpath, "vendored", f"directory name {dirname}")
                )
                continue
            if dirname in GENERATED_DIR_NAMES:
                entries.append(
                    directory_entry(root, relpath, "generated", f"directory name {dirname}")
                )
                continue
            matched = match_gitattributes(rules, relpath + "/")
            if matched is not None:
                entries.append(directory_entry(root, relpath, matched[0], matched[1]))
                continue
            keep.append(dirname)
        dirnames[:] = keep

        for filename in sorted(filenames):
            fullpath = os.path.join(dirpath, filename)
            if os.path.islink(fullpath):
                continue
            relpath = filename if relative_dir == "." else f"{relative_dir}/{filename}"
            relpath = relpath.replace(os.sep, "/")
            walked += 1
            matched = match_gitattributes(rules, relpath)
            if matched is not None:
                try:
                    size = os.stat(fullpath).st_size
                except OSError:
                    skipped_unreadable += 1
                    continue
                entries.append(
                    {
                        "path": relpath,
                        "category": matched[0],
                        "bytes": size,
                        "evidence": matched[1],
                    }
                )
                continue
            try:
                entry = classify_file(root, relpath)
            except OSError:
                skipped_unreadable += 1
                continue
            if entry is not None:
                entries.append(entry)

    entries.sort(key=lambda entry: entry["path"])
    counts = {"files_walked": walked, "files_skipped_unreadable": skipped_unreadable}
    for entry in entries:
        key = "bytes_" + entry["category"]
        counts[key] = counts.get(key, 0) + entry["bytes"]
    return {"entries": entries, "counts": counts}


BOUNDARY_RELPATH = ".horos/boundary.json"
BOUNDARY_SCHEMA = 1

# Printed after a boundary write, for the adopting repository's AGENTS.md or
# CLAUDE.md. This is the whole bridge to agents that have never heard of
# Horos: harnesses load those files at session start, so the discipline
# travels with the repository instead of with this skill.
ADOPTION_STANZA = """\
Paste this into the repository's AGENTS.md or CLAUDE.md so agents without
Horos inherit the boundary:

## Reading boundary

Before reading this repository broadly, consult `.horos/boundary.json`.
Every path listed there is a classified token sink carrying the evidence
that earned its entry; leave those paths unread unless the task demands
one. The boundary is fail-open: what it omits is merely unproven. It never
applies during security review; during any audit, review or incident work,
read as if no boundary exists.
"""


def boundary_document(result):
    """The committed artefact: schema-tagged, no timestamps, no absolute paths."""
    return {
        "schema": BOUNDARY_SCHEMA,
        "tool": "horos",
        "entries": result["entries"],
        "counts": result["counts"],
    }


def render(document):
    """One canonical byte form, so equal documents are equal files."""
    return json.dumps(document, indent=2, sort_keys=True) + "\n"


def write_boundary(root, document):
    """Write atomically: a killed run leaves the old boundary or the new one."""
    directory = os.path.join(root, os.path.dirname(BOUNDARY_RELPATH))
    os.makedirs(directory, exist_ok=True)
    final = os.path.join(root, BOUNDARY_RELPATH)
    # Per-process name: two concurrent scans must not unlink each other's
    # half-written temporary in the finally block below.
    temporary = f"{final}.{os.getpid()}.tmp"
    try:
        with open(temporary, "w", encoding="utf-8") as handle:
            handle.write(render(document))
        os.replace(temporary, final)
    finally:
        if os.path.exists(temporary):
            os.unlink(temporary)


def load_boundary(root):
    with open(os.path.join(root, BOUNDARY_RELPATH), encoding="utf-8") as handle:
        return json.load(handle)


def diff_documents(committed, fresh):
    """Name every drifted path; a symmetric compare, so a committed entry the
    tree no longer evidences drifts exactly like a new sink the boundary lacks.
    """
    old = {entry["path"]: entry for entry in committed.get("entries", [])}
    new = {entry["path"]: entry for entry in fresh.get("entries", [])}
    drifted = []
    for path in sorted(set(old) | set(new)):
        if path not in new:
            drifted.append((path, "in the boundary but no longer evidenced by the tree"))
        elif path not in old:
            drifted.append((path, "evidenced by the tree but missing from the boundary"))
        elif old[path] != new[path]:
            drifted.append((path, "entry changed: %s -> %s" % (old[path], new[path])))
    return drifted


def check_tree(root, out=None):
    out = out if out is not None else sys.stdout
    try:
        committed = load_boundary(root)
    except FileNotFoundError:
        print(f"horos: no boundary at {BOUNDARY_RELPATH}; run scan --write", file=out)
        return 2
    except (OSError, json.JSONDecodeError) as error:
        print(f"horos: unreadable boundary: {error}", file=out)
        return 2
    fresh = boundary_document(scan_tree(root))
    drifted = diff_documents(committed, fresh)
    if not drifted:
        print("boundary matches the tree", file=out)
        return 0
    for path, reason in drifted:
        print(f"drift: {path}: {reason}", file=out)
    print(f"{len(drifted)} path(s) drifted", file=out)
    return 1


def map_file(path, out=None):
    """Print a file's skeleton via its language extractor; orientation
    without the read."""
    out = out if out is not None else sys.stdout
    extractor = None
    for suffix in sorted(languages.EXTRACTORS, key=len, reverse=True):
        if path.endswith(suffix):
            extractor = languages.EXTRACTORS[suffix]
            break
    if extractor is None:
        print(f"horos: map supports {languages.supported()}, not {path}", file=out)
        return 2
    try:
        with open(path, "rb") as handle:
            source = handle.read().decode("utf-8", errors="replace")
    except OSError as error:
        print(f"horos: cannot read {path}: {error}", file=out)
        return 2
    return extractor(path, source, out)


def main(argv=None):
    parser = argparse.ArgumentParser(prog="horos", description=__doc__)
    subparsers = parser.add_subparsers(dest="command", required=True)
    scan = subparsers.add_parser("scan", help="classify a tree")
    scan.add_argument("root", help="directory to scan")
    scan.add_argument(
        "--json", action="store_true", help="print the boundary document"
    )
    scan.add_argument(
        "--write", action="store_true", help=f"write {BOUNDARY_RELPATH} atomically"
    )
    checker = subparsers.add_parser("check", help="verify the committed boundary")
    checker.add_argument("root", help="directory to check")
    mapper = subparsers.add_parser("map", help="print a Python file's skeleton")
    mapper.add_argument("file", help="Python file to map")
    args = parser.parse_args(argv)

    if args.command == "map":
        return map_file(args.file)

    if not os.path.isdir(args.root):
        print(f"horos: not a directory: {args.root}", file=sys.stderr)
        return 2

    if args.command == "check":
        return check_tree(args.root)

    document = boundary_document(scan_tree(args.root))
    if args.write:
        write_boundary(args.root, document)
    if args.json:
        sys.stdout.write(render(document))
    else:
        for key, value in sorted(document["counts"].items()):
            print(f"{key}: {value}")
        print(f"entries: {len(document['entries'])}")
        if args.write:
            print()
            print(ADOPTION_STANZA, end="")
    return 0


if __name__ == "__main__":
    sys.exit(main())
