"""Horos: classify a repository's token sinks and emit the reading boundary.

scan <root>   walk a tree, classify every file it can evidence, print JSON

Classification is fail-open: a file the rules cannot evidence stays readable
and earns no entry. The scanner stats every file but reads at most
PREFIX_BYTES of any of them, so a scan never costs more than a fraction of
what it saves.
"""

from pathlib import PurePosixPath
import argparse
import fnmatch
import json
import os
import sys

# The classifier's own reading limit. Raising it is an ask-first change once
# the tests pin it: every content rule below is defined against this prefix.
PREFIX_BYTES = 4096

# Geometry thresholds for data blobs and minified bundles. A small file is
# never a blob entry; whatever it costs, it costs almost nothing.
BLOB_MIN_BYTES = 16384
MINIFIED_MEAN_LINE_LENGTH = 400

LOCKFILE_NAMES = frozenset(
    {
        "bun.lockb",
        "Cargo.lock",
        "composer.lock",
        "flake.lock",
        "Gemfile.lock",
        "go.sum",
        "package-lock.json",
        "packages.lock.json",
        "Pipfile.lock",
        "pnpm-lock.yaml",
        "poetry.lock",
        "uv.lock",
        "yarn.lock",
    }
)

GENERATED_MARKERS = (
    "do not edit",
    "@generated",
    "code generated by",
    "auto-generated",
    "autogenerated",
    "automatically generated",
)

GENERATED_DIR_NAMES = frozenset({"build", "dist", "out", "storybook-static"})

VENDORED_DIR_NAMES = frozenset(
    {"bower_components", "node_modules", "third_party", "thirdparty", "vendor", "vendored"}
)

# Never walked, never listed: not source and not a sink worth recording.
SKIPPED_DIR_NAMES = frozenset({".git", ".horos", "__pycache__"})


def read_prefix(path):
    """Return the first PREFIX_BYTES of the file, raw."""
    with open(path, "rb") as handle:
        return handle.read(PREFIX_BYTES)


def gitattributes_rules(root):
    """Parse linguist-vendored and linguist-generated patterns, fail-open.

    Only the repository-root .gitattributes is consulted, and only patterns
    whose attribute is an unnegated linguist-vendored or linguist-generated.
    Anything unparseable is skipped rather than guessed at.
    """
    rules = []
    path = os.path.join(root, ".gitattributes")
    if not os.path.isfile(path) or os.path.islink(path):
        return rules
    try:
        text = read_prefix(path).decode("utf-8", errors="replace")
    except OSError:
        return rules
    for line in text.splitlines():
        parts = line.split()
        if len(parts) < 2 or parts[0].startswith("#"):
            continue
        for category, attribute in (
            ("vendored", "linguist-vendored"),
            ("generated", "linguist-generated"),
        ):
            if attribute in parts[1:] or f"{attribute}=true" in parts[1:]:
                rules.append((parts[0].lstrip("/"), category, attribute))
    return rules


def match_gitattributes(rules, relpath):
    for pattern, category, attribute in rules:
        candidates = [pattern]
        if pattern.endswith("/**"):
            candidates.append(pattern[: -len("/**")] + "/*")
        for candidate in candidates:
            if fnmatch.fnmatch(relpath, candidate) or fnmatch.fnmatch(
                PurePosixPath(relpath).name, candidate
            ):
                return category, f"{attribute} for {pattern!r} in .gitattributes"
    return None


def classify_content(name, size, prefix):
    """Content rules over the bounded prefix, most decisive first.

    Returns (category, evidence) or None. Order matters: a null byte makes
    every later text heuristic meaningless, so binary wins outright.
    """
    if b"\x00" in prefix:
        return "binary", "null byte in the first %d bytes" % PREFIX_BYTES

    text = prefix.decode("utf-8", errors="replace")
    lowered = text.lower()
    for marker in GENERATED_MARKERS:
        if marker in lowered:
            return "generated", f"marker {marker!r} in the first {PREFIX_BYTES} bytes"

    if name.endswith(".map") and '"mappings"' in text:
        return "generated", 'sourcemap: name ends .map and prefix carries "mappings"'

    if size >= BLOB_MIN_BYTES:
        newlines = prefix.count(b"\n")
        if newlines == 0:
            return "blob", f"no newline in the first {PREFIX_BYTES} bytes of {size} bytes"
        if len(prefix) // (newlines + 1) > MINIFIED_MEAN_LINE_LENGTH:
            return (
                "blob",
                "mean line length above %d in the first %d bytes"
                % (MINIFIED_MEAN_LINE_LENGTH, PREFIX_BYTES),
            )
    return None


def classify_file(root, relpath):
    """Classify one file; None means it stays readable.

    Raises OSError when the file cannot be statted or read, so the caller
    can count it as skipped rather than silently readable. Symlinks are
    refused here as well as in the walk: this function is public, and a
    caller handing it a link must not make the scanner read outside root.
    """
    fullpath = os.path.join(root, relpath)
    if os.path.islink(fullpath):
        return None
    name = PurePosixPath(relpath).name
    size = os.stat(fullpath).st_size

    if name in LOCKFILE_NAMES:
        return {
            "path": relpath,
            "category": "lockfile",
            "bytes": size,
            "evidence": f"lockfile name {name}",
        }

    prefix = read_prefix(fullpath)
    verdict = classify_content(name, size, prefix)
    if verdict is None:
        return None
    category, evidence = verdict
    return {"path": relpath, "category": category, "bytes": size, "evidence": evidence}


def directory_entry(root, relpath, category, evidence):
    """Aggregate a vendored or generated directory into one entry."""
    total = 0
    files = 0
    for dirpath, dirnames, filenames in os.walk(
        os.path.join(root, relpath), followlinks=False
    ):
        dirnames[:] = sorted(d for d in dirnames if d not in SKIPPED_DIR_NAMES)
        for filename in sorted(filenames):
            fullpath = os.path.join(dirpath, filename)
            if os.path.islink(fullpath):
                continue
            try:
                total += os.stat(fullpath).st_size
            except OSError:
                continue
            files += 1
    return {
        "path": relpath + "/",
        "category": category,
        "bytes": total,
        "files": files,
        "evidence": evidence,
    }


def scan_tree(root):
    """Walk the tree and return entries plus the counts a quiet run reports."""
    root = os.path.abspath(root)
    rules = gitattributes_rules(root)
    entries = []
    walked = 0
    skipped_unreadable = 0

    for dirpath, dirnames, filenames in os.walk(root, followlinks=False):
        relative_dir = os.path.relpath(dirpath, root)
        keep = []
        for dirname in sorted(dirnames):
            if dirname in SKIPPED_DIR_NAMES:
                continue
            child = os.path.join(dirpath, dirname)
            if os.path.islink(child):
                continue
            relpath = dirname if relative_dir == "." else f"{relative_dir}/{dirname}"
            relpath = relpath.replace(os.sep, "/")
            if dirname in VENDORED_DIR_NAMES:
                entries.append(
                    directory_entry(root, relpath, "vendored", f"directory name {dirname}")
                )
                continue
            if dirname in GENERATED_DIR_NAMES:
                entries.append(
                    directory_entry(root, relpath, "generated", f"directory name {dirname}")
                )
                continue
            matched = match_gitattributes(rules, relpath + "/")
            if matched is not None:
                entries.append(directory_entry(root, relpath, matched[0], matched[1]))
                continue
            keep.append(dirname)
        dirnames[:] = keep

        for filename in sorted(filenames):
            fullpath = os.path.join(dirpath, filename)
            if os.path.islink(fullpath):
                continue
            relpath = filename if relative_dir == "." else f"{relative_dir}/{filename}"
            relpath = relpath.replace(os.sep, "/")
            walked += 1
            matched = match_gitattributes(rules, relpath)
            if matched is not None:
                try:
                    size = os.stat(fullpath).st_size
                except OSError:
                    skipped_unreadable += 1
                    continue
                entries.append(
                    {
                        "path": relpath,
                        "category": matched[0],
                        "bytes": size,
                        "evidence": matched[1],
                    }
                )
                continue
            try:
                entry = classify_file(root, relpath)
            except OSError:
                skipped_unreadable += 1
                continue
            if entry is not None:
                entries.append(entry)

    entries.sort(key=lambda entry: entry["path"])
    counts = {"files_walked": walked, "files_skipped_unreadable": skipped_unreadable}
    for entry in entries:
        key = "bytes_" + entry["category"]
        counts[key] = counts.get(key, 0) + entry["bytes"]
    return {"entries": entries, "counts": counts}


def main(argv=None):
    parser = argparse.ArgumentParser(prog="horos", description=__doc__)
    subparsers = parser.add_subparsers(dest="command", required=True)
    scan = subparsers.add_parser("scan", help="classify a tree and print JSON")
    scan.add_argument("root", help="directory to scan")
    args = parser.parse_args(argv)

    if not os.path.isdir(args.root):
        print(f"horos: not a directory: {args.root}", file=sys.stderr)
        return 2
    result = scan_tree(args.root)
    json.dump(result, sys.stdout, indent=2, sort_keys=True)
    print()
    return 0


if __name__ == "__main__":
    sys.exit(main())
