"""Every classifier rule earns its entry, and every near-miss stays readable."""

from pathlib import Path
import os
import sys
import tempfile
import unittest

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "skills" / "horos" / "scripts"))  # noqa: E402  (locates horos.py)

import horos  # noqa: E402


def write(root, relpath, content):
    path = Path(root) / relpath
    path.parent.mkdir(parents=True, exist_ok=True)
    if isinstance(content, str):
        content = content.encode("utf-8")
    path.write_bytes(content)
    return path


class ClassifyTests(unittest.TestCase):
    def setUp(self):
        self._tmp = tempfile.TemporaryDirectory()
        self.root = self._tmp.name
        self.addCleanup(self._tmp.cleanup)

    def entries(self):
        return {entry["path"]: entry for entry in horos.scan_tree(self.root)["entries"]}

    def test_a_null_byte_in_the_prefix_is_binary(self):
        write(self.root, "logo.png", b"\x89PNG\x00\x1a")
        self.assertEqual(self.entries()["logo.png"]["category"], "binary")

    def test_plain_text_is_not_binary(self):
        write(self.root, "notes.txt", "plain words\n")
        self.assertNotIn("notes.txt", self.entries())

    def test_a_lockfile_is_named_as_such(self):
        write(self.root, "package-lock.json", '{"lockfileVersion": 3}\n')
        entry = self.entries()["package-lock.json"]
        self.assertEqual(entry["category"], "lockfile")
        self.assertIn("package-lock.json", entry["evidence"])

    def test_an_ordinary_json_file_is_not_a_lockfile(self):
        write(self.root, "config.json", '{"a": 1}\n')
        self.assertNotIn("config.json", self.entries())

    def test_a_generation_marker_in_the_prefix_is_generated(self):
        write(self.root, "api.py", "# Code generated by protoc. DO NOT EDIT.\nx = 1\n")
        entry = self.entries()["api.py"]
        self.assertEqual(entry["category"], "generated")
        self.assertIn("first 4096 bytes", entry["evidence"])

    def test_a_marker_beyond_the_prefix_stays_readable(self):
        write(self.root, "deep.py", "x = 1\n" * 1000 + "# DO NOT EDIT\n")
        self.assertNotIn("deep.py", self.entries())

    def test_a_generated_directory_becomes_one_entry(self):
        write(self.root, "dist/app.js", "var a=1;\n")
        write(self.root, "dist/nested/app.css", "body{}\n")
        entry = self.entries()["dist/"]
        self.assertEqual(entry["category"], "generated")
        self.assertEqual(entry["files"], 2)
        self.assertEqual(entry["bytes"], 9 + 7)

    def test_a_near_miss_directory_name_stays_readable(self):
        write(self.root, "builder/main.py", "x = 1\n")
        self.assertNotIn("builder/", self.entries())
        self.assertNotIn("builder/main.py", self.entries())

    def test_a_vendored_directory_becomes_one_entry(self):
        write(self.root, "node_modules/left-pad/index.js", "module.exports = 1\n")
        entry = self.entries()["node_modules/"]
        self.assertEqual(entry["category"], "vendored")
        self.assertEqual(entry["files"], 1)

    def test_a_sourcemap_is_generated(self):
        write(self.root, "app.js.map", '{"version":3,"mappings":"AAAA"}')
        self.assertEqual(self.entries()["app.js.map"]["category"], "generated")

    def test_a_map_file_without_mappings_stays_readable(self):
        write(self.root, "site.map", "sitemap: not a sourcemap\n")
        self.assertNotIn("site.map", self.entries())

    def test_a_large_single_line_file_is_a_blob(self):
        write(self.root, "data.json", "x" * (horos.BLOB_MIN_BYTES + 1))
        entry = self.entries()["data.json"]
        self.assertEqual(entry["category"], "blob")
        self.assertIn("no newline", entry["evidence"])

    def test_a_small_single_line_file_stays_readable(self):
        write(self.root, "small.json", "x" * 100)
        self.assertNotIn("small.json", self.entries())

    def test_minified_line_geometry_is_a_blob(self):
        line = "a" * 800 + "\n"
        write(self.root, "bundle.js", line * 40)
        entry = self.entries()["bundle.js"]
        self.assertEqual(entry["category"], "blob")
        self.assertIn("mean line length", entry["evidence"])

    def test_ordinary_code_geometry_stays_readable(self):
        write(self.root, "module.py", ("x = 1\n" * 40) * 100)
        self.assertNotIn("module.py", self.entries())

    def test_gitattributes_vendored_patterns_are_honoured(self):
        write(self.root, ".gitattributes", "lib/** linguist-vendored\n")
        write(self.root, "lib/dep.py", "x = 1\n")
        entry = self.entries()["lib/"]
        self.assertEqual(entry["category"], "vendored")
        self.assertIn(".gitattributes", entry["evidence"])

    def test_a_symlink_out_of_the_root_is_never_followed(self):
        outside = tempfile.TemporaryDirectory()
        self.addCleanup(outside.cleanup)
        write(outside.name, "secret.bin", b"\x00" * 20)
        os.symlink(outside.name, os.path.join(self.root, "escape"))
        os.symlink(
            os.path.join(outside.name, "secret.bin"),
            os.path.join(self.root, "alias.bin"),
        )
        result = horos.scan_tree(self.root)
        self.assertEqual(result["entries"], [])
        self.assertEqual(result["counts"]["files_walked"], 0)

    def test_undecodable_bytes_never_raise(self):
        write(self.root, "latin.txt", b"caf\xe9 " * 3000)
        horos.scan_tree(self.root)

    def test_git_and_horos_directories_are_never_scanned(self):
        write(self.root, ".git/objects/blob", b"\x00")
        write(self.root, ".horos/boundary.json", "{}")
        write(self.root, "__pycache__/mod.cpython-311.pyc", b"\x00")
        result = horos.scan_tree(self.root)
        self.assertEqual(result["entries"], [])
        self.assertEqual(result["counts"]["files_walked"], 0)

    def test_the_walk_is_deterministic(self):
        write(self.root, "b/data.bin", b"\x00")
        write(self.root, "a/yarn.lock", "lock\n")
        write(self.root, "dist/x.js", "var a;\n")
        first = horos.scan_tree(self.root)
        second = horos.scan_tree(self.root)
        self.assertEqual(first, second)
        paths = [entry["path"] for entry in first["entries"]]
        self.assertEqual(paths, sorted(paths))

    def test_an_unreadable_file_is_counted_as_skipped_not_readable(self):
        path = write(self.root, "locked.txt", "cannot read me\n")
        os.chmod(path, 0)
        self.addCleanup(os.chmod, path, 0o644)
        result = horos.scan_tree(self.root)
        self.assertEqual(result["counts"]["files_skipped_unreadable"], 1)
        self.assertEqual(result["entries"], [])

    def test_counts_report_bytes_per_category(self):
        write(self.root, "a.bin", b"\x00" * 10)
        write(self.root, "yarn.lock", "lock\n")
        counts = horos.scan_tree(self.root)["counts"]
        self.assertEqual(counts["bytes_binary"], 10)
        self.assertEqual(counts["bytes_lockfile"], 5)
        self.assertEqual(counts["files_walked"], 2)


if __name__ == "__main__":
    unittest.main()
